apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: log4shell-patch
  namespace: zta-demo
spec:
  selector:
    matchLabels:
      language: java
  url: oci://${WASM_HUB}/log4shell-patch:${TAG}
  imagePullPolicy: Always
