apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vulnerable
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: ingress-tls-cert
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vulnerable
spec:
  hosts:
  - "*"
  gateways:
  - vulnerable
  http:
  - route:
    - destination:
        host: vulnerable
        port:
          number: 8080
