apiVersion: v1
kind: Service
metadata:
  name: log4shell
  labels:
    app: log4shell
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
    - port: 1389
      targetPort: 1389
      name: tcp-ldap      
  selector:
    app: log4shell
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: log4shell
  labels:
    app: log4shell
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4shell
  labels:
    app: log4shell
spec:
  selector:
    matchLabels:
      app: log4shell
  template:
    metadata:
      labels:
        app: log4shell
    spec:
      serviceAccountName: log4shell
      containers:
        - name: log4shell-ldap
          image: ${HUB}/log4shell-ldap:${TAG}
          imagePullPolicy: Always
          env:
            - name: publicIp
              value: log4shell
          ports:
            - name: http
              containerPort: 3000
            - name: tcp-ldap
              containerPort: 1389
