apiVersion: v1
kind: Service
metadata:
  name: vulnerable
  labels:
    app: vulnerable
    language: java
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: vulnerable
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vulnerable
  labels:
    app: vulnerable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable
  labels:
    app: vulnerable
    language: java
spec:
  selector:
    matchLabels:
      app: vulnerable
  template:
    metadata:
      annotations:
        sidecar.istio.io/logLevel: "jwt:debug,ext_authz:debug,rbac:debug,wasm:debug"
      labels:
        app: vulnerable
        language: java
    spec:
      serviceAccountName: vulnerable
      containers:
        - name: vulnerable
          image: ${HUB}/vulnerable:${TAG}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
