resolvers:
  principal:
    - name: jwt_bearer
      params:
        header: authorization
        prefix: "Bearer "
        subject-claim: "https://zta-demo/group"
  operation:
    - name: method
  resource:
    - name: request_path
